import { format, fromUnixTime, isToday, isTomorrow } from 'date-fns';

export default async function fetchApiData(location) {
   const coordinates = await getLocationCoordinates(location);
   const apiData = await getApiWeatherData(coordinates);

   const processedData = processFetchedData(apiData);

   return apiData;
}

async function getLocationCoordinates(location) {
   const response = await fetch(
      `https://api.openweathermap.org/geo/1.0/direct?q=${location}&limit=1&appid=163a88340501cc3338e7b7a9919e470f`
   );

   const coordinatesJson = await response.json();
   return coordinatesJson[0];
}

// async function getYesterdayWeatherData(coordinates) {
//    const yesterday = new Date().setDate(new Date().getDate() - 1);
//    const formattedYesterday = format(yesterday, 'yyyy-MM-dd');

//    const apiData = await fetch(
//       `https://api.openweathermap.org/data/3.0/onecall/day_summary?lat=${coordinates.lat}&lon=${coordinates.lon}&date=${formattedYesterday}&units=metric&appid=163a88340501cc3338e7b7a9919e470f`
//    );

//    const apiDataJson = await apiData.json();
//    return apiDataJson;
// }

async function getApiWeatherData(coordinates) {
   const response = await fetch(
      `https://api.openweathermap.org/data/3.0/onecall?lat=${coordinates.lat}&lon=${coordinates.lon}&units=metric&appid=163a88340501cc3338e7b7a9919e470f`
   );

   const apiData = await response.json();
   return apiData;
}

function processFetchedData(apiData) {
   const processedData = {
      current: {
         temp: apiData.current.temp,
         feels_like: apiData.current.feels_like,
         humidity: apiData.current.humidity,
      },

      today: {
         humidity: apiData.daily[0].humidity,
         wind_speed: apiData.daily[0].wind_speed,
         wind_deg: apiData.daily[0].wind_deg,
         sunrise: fromUnixTime(apiData.daily[0].sunrise),
         sunset: fromUnixTime(apiData.daily[0].sunset),
         pressure: apiData.daily[0].pressure,
         uvi: apiData.daily[0].uvi,
         precipitation: apiData.daily[0].pop * 100,
      },

      daily: [],
   };

   for (let i = 0; i <= 7; i++) {
      const day = fromUnixTime(apiData.daily[i].dt);
      const dayData = {
         icon: apiData.daily[i].weather[0].icon,
         main: apiData.daily[i].weather[0].main,
         temp: {
            max: apiData.daily[i].temp.max,
            min: apiData.daily[i].temp.min,
         },
      };

      if (isToday(day)) {
         dayData.day = 'Today';
      } else if (isTomorrow(day)) {
         dayData.day = 'Tomorrow';
      } else {
         dayData.day = format(day, 'EEEE');
      }
      processedData.daily.push(dayData);
   }

   return processedData;
}

const response = {
   lat: 36.4074,
   lon: 5.942,
   timezone: 'Africa/Algiers',
   timezone_offset: 3600,
   current: {
      dt: 1692374480,
      sunrise: 1692334570,
      sunset: 1692383070,
      temp: 36.78,
      feels_like: 35.49,
      pressure: 1013,
      humidity: 22,
      dew_point: 11.59,
      uvi: 1.84,
      clouds: 12,
      visibility: 10000,
      wind_speed: 5.05,
      wind_deg: 357,
      wind_gust: 5.72,
      weather: [
         {
            id: 801,
            main: 'Clouds',
            description: 'few clouds',
            icon: '02d',
         },
      ],
   },
   hourly: [
      {
         dt: 1692374400,
         temp: 36.78,
         feels_like: 35.49,
         pressure: 1013,
         humidity: 22,
         dew_point: 11.59,
         uvi: 1.84,
         clouds: 12,
         visibility: 10000,
         wind_speed: 5.05,
         wind_deg: 357,
         wind_gust: 5.72,
         weather: [
            {
               id: 801,
               main: 'Clouds',
               description: 'few clouds',
               icon: '02d',
            },
         ],
         pop: 0,
      },
      {
         dt: 1692378000,
         temp: 36.36,
         feels_like: 35.14,
         pressure: 1013,
         humidity: 23,
         dew_point: 11.92,
         uvi: 0.55,
         clouds: 13,
         visibility: 10000,
         wind_speed: 4.69,
         wind_deg: 6,
         wind_gust: 4.49,
         weather: [
            {
               id: 801,
               main: 'Clouds',
               description: 'few clouds',
               icon: '02d',
            },
         ],
         pop: 0,
      },
      {
         dt: 1692381600,
         temp: 35.1,
         feels_like: 34.04,
         pressure: 1013,
         humidity: 26,
         dew_point: 12.73,
         uvi: 0,
         clouds: 15,
         visibility: 10000,
         wind_speed: 3.32,
         wind_deg: 16,
         wind_gust: 3.42,
         weather: [
            {
               id: 801,
               main: 'Clouds',
               description: 'few clouds',
               icon: '02d',
            },
         ],
         pop: 0,
      },
      {
         dt: 1692385200,
         temp: 32.83,
         feels_like: 32.08,
         pressure: 1014,
         humidity: 32,
         dew_point: 13.97,
         uvi: 0,
         clouds: 5,
         visibility: 10000,
         wind_speed: 2.43,
         wind_deg: 32,
         wind_gust: 2.72,
         weather: [
            {
               id: 800,
               main: 'Clear',
               description: 'clear sky',
               icon: '01n',
            },
         ],
         pop: 0,
      },
      {
         dt: 1692388800,
         temp: 30.63,
         feels_like: 30.19,
         pressure: 1015,
         humidity: 38,
         dew_point: 14.7,
         uvi: 0,
         clouds: 2,
         visibility: 10000,
         wind_speed: 1.69,
         wind_deg: 43,
         wind_gust: 1.84,
         weather: [
            {
               id: 800,
               main: 'Clear',
               description: 'clear sky',
               icon: '01n',
            },
         ],
         pop: 0,
      },
      {
         dt: 1692392400,
         temp: 28.46,
         feels_like: 28.24,
         pressure: 1017,
         humidity: 42,
         dew_point: 13.32,
         uvi: 0,
         clouds: 0,
         visibility: 10000,
         wind_speed: 0.93,
         wind_deg: 64,
         wind_gust: 1.09,
         weather: [
            {
               id: 800,
               main: 'Clear',
               description: 'clear sky',
               icon: '01n',
            },
         ],
         pop: 0,
      },
      {
         dt: 1692396000,
         temp: 28.11,
         feels_like: 27.91,
         pressure: 1016,
         humidity: 42,
         dew_point: 13.21,
         uvi: 0,
         clouds: 0,
         visibility: 10000,
         wind_speed: 0.66,
         wind_deg: 141,
         wind_gust: 0.87,
         weather: [
            {
               id: 800,
               main: 'Clear',
               description: 'clear sky',
               icon: '01n',
            },
         ],
         pop: 0,
      },
      {
         dt: 1692399600,
         temp: 27.82,
         feels_like: 27.64,
         pressure: 1016,
         humidity: 42,
         dew_point: 13.02,
         uvi: 0,
         clouds: 0,
         visibility: 10000,
         wind_speed: 0.45,
         wind_deg: 199,
         wind_gust: 0.66,
         weather: [
            {
               id: 800,
               main: 'Clear',
               description: 'clear sky',
               icon: '01n',
            },
         ],
         pop: 0,
      },
      {
         dt: 1692403200,
         temp: 27.52,
         feels_like: 27.45,
         pressure: 1015,
         humidity: 43,
         dew_point: 12.87,
         uvi: 0,
         clouds: 0,
         visibility: 10000,
         wind_speed: 0.22,
         wind_deg: 138,
         wind_gust: 0.46,
         weather: [
            {
               id: 800,
               main: 'Clear',
               description: 'clear sky',
               icon: '01n',
            },
         ],
         pop: 0,
      },
      {
         dt: 1692406800,
         temp: 27.25,
         feels_like: 27.22,
         pressure: 1015,
         humidity: 43,
         dew_point: 12.62,
         uvi: 0,
         clouds: 0,
         visibility: 10000,
         wind_speed: 0.89,
         wind_deg: 147,
         wind_gust: 1.03,
         weather: [
            {
               id: 800,
               main: 'Clear',
               description: 'clear sky',
               icon: '01n',
            },
         ],
         pop: 0,
      },
      {
         dt: 1692410400,
         temp: 27.03,
         feels_like: 27.04,
         pressure: 1015,
         humidity: 43,
         dew_point: 12.52,
         uvi: 0,
         clouds: 0,
         visibility: 10000,
         wind_speed: 1.08,
         wind_deg: 161,
         wind_gust: 1.13,
         weather: [
            {
               id: 800,
               main: 'Clear',
               description: 'clear sky',
               icon: '01n',
            },
         ],
         pop: 0,
      },
      {
         dt: 1692414000,
         temp: 26.66,
         feels_like: 26.66,
         pressure: 1014,
         humidity: 44,
         dew_point: 12.43,
         uvi: 0,
         clouds: 0,
         visibility: 10000,
         wind_speed: 0.44,
         wind_deg: 73,
         wind_gust: 0.9,
         weather: [
            {
               id: 800,
               main: 'Clear',
               description: 'clear sky',
               icon: '01n',
            },
         ],
         pop: 0,
      },
      {
         dt: 1692417600,
         temp: 26.04,
         feels_like: 26.04,
         pressure: 1015,
         humidity: 45,
         dew_point: 12.37,
         uvi: 0,
         clouds: 0,
         visibility: 10000,
         wind_speed: 0.85,
         wind_deg: 318,
         wind_gust: 0.93,
         weather: [
            {
               id: 800,
               main: 'Clear',
               description: 'clear sky',
               icon: '01n',
            },
         ],
         pop: 0,
      },
      {
         dt: 1692421200,
         temp: 25.64,
         feels_like: 25.46,
         pressure: 1015,
         humidity: 46,
         dew_point: 12.16,
         uvi: 0,
         clouds: 0,
         visibility: 10000,
         wind_speed: 1.15,
         wind_deg: 327,
         wind_gust: 1.16,
         weather: [
            {
               id: 800,
               main: 'Clear',
               description: 'clear sky',
               icon: '01d',
            },
         ],
         pop: 0,
      },
      {
         dt: 1692424800,
         temp: 27.4,
         feels_like: 27.22,
         pressure: 1015,
         humidity: 41,
         dew_point: 12.34,
         uvi: 0.35,
         clouds: 0,
         visibility: 10000,
         wind_speed: 1.55,
         wind_deg: 338,
         wind_gust: 1.49,
         weather: [
            {
               id: 800,
               main: 'Clear',
               description: 'clear sky',
               icon: '01d',
            },
         ],
         pop: 0,
      },
      {
         dt: 1692428400,
         temp: 29.23,
         feels_like: 28.49,
         pressure: 1016,
         humidity: 36,
         dew_point: 11.91,
         uvi: 1.35,
         clouds: 0,
         visibility: 10000,
         wind_speed: 1.74,
         wind_deg: 348,
         wind_gust: 1.85,
         weather: [
            {
               id: 800,
               main: 'Clear',
               description: 'clear sky',
               icon: '01d',
            },
         ],
         pop: 0,
      },
      {
         dt: 1692432000,
         temp: 30.56,
         feels_like: 29.56,
         pressure: 1016,
         humidity: 33,
         dew_point: 11.5,
         uvi: 3.21,
         clouds: 0,
         visibility: 10000,
         wind_speed: 2.04,
         wind_deg: 356,
         wind_gust: 1.99,
         weather: [
            {
               id: 800,
               main: 'Clear',
               description: 'clear sky',
               icon: '01d',
            },
         ],
         pop: 0,
      },
      {
         dt: 1692435600,
         temp: 31.92,
         feels_like: 30.62,
         pressure: 1017,
         humidity: 29,
         dew_point: 10.68,
         uvi: 5.68,
         clouds: 0,
         visibility: 10000,
         wind_speed: 2.89,
         wind_deg: 7,
         wind_gust: 2.64,
         weather: [
            {
               id: 800,
               main: 'Clear',
               description: 'clear sky',
               icon: '01d',
            },
         ],
         pop: 0,
      },
      {
         dt: 1692439200,
         temp: 33.05,
         feels_like: 31.43,
         pressure: 1017,
         humidity: 25,
         dew_point: 9.79,
         uvi: 8.02,
         clouds: 0,
         visibility: 10000,
         wind_speed: 3.45,
         wind_deg: 11,
         wind_gust: 2.92,
         weather: [
            {
               id: 800,
               main: 'Clear',
               description: 'clear sky',
               icon: '01d',
            },
         ],
         pop: 0,
      },
      {
         dt: 1692442800,
         temp: 34.06,
         feels_like: 32.23,
         pressure: 1016,
         humidity: 22,
         dew_point: 8.91,
         uvi: 9.57,
         clouds: 0,
         visibility: 10000,
         wind_speed: 3.58,
         wind_deg: 13,
         wind_gust: 2.97,
         weather: [
            {
               id: 800,
               main: 'Clear',
               description: 'clear sky',
               icon: '01d',
            },
         ],
         pop: 0,
      },
      {
         dt: 1692446400,
         temp: 34.94,
         feels_like: 32.98,
         pressure: 1016,
         humidity: 20,
         dew_point: 8.34,
         uvi: 9.77,
         clouds: 0,
         visibility: 10000,
         wind_speed: 3.95,
         wind_deg: 17,
         wind_gust: 3.17,
         weather: [
            {
               id: 800,
               main: 'Clear',
               description: 'clear sky',
               icon: '01d',
            },
         ],
         pop: 0,
      },
      {
         dt: 1692450000,
         temp: 35.54,
         feels_like: 33.53,
         pressure: 1016,
         humidity: 19,
         dew_point: 7.97,
         uvi: 8.56,
         clouds: 1,
         visibility: 10000,
         wind_speed: 4.37,
         wind_deg: 21,
         wind_gust: 3.5,
         weather: [
            {
               id: 800,
               main: 'Clear',
               description: 'clear sky',
               icon: '01d',
            },
         ],
         pop: 0,
      },
      {
         dt: 1692453600,
         temp: 35.66,
         feels_like: 33.66,
         pressure: 1015,
         humidity: 19,
         dew_point: 7.84,
         uvi: 6.34,
         clouds: 1,
         visibility: 10000,
         wind_speed: 4.47,
         wind_deg: 22,
         wind_gust: 3.72,
         weather: [
            {
               id: 800,
               main: 'Clear',
               description: 'clear sky',
               icon: '01d',
            },
         ],
         pop: 0,
      },
      {
         dt: 1692457200,
         temp: 35.4,
         feels_like: 33.5,
         pressure: 1015,
         humidity: 20,
         dew_point: 8.13,
         uvi: 3.83,
         clouds: 1,
         visibility: 10000,
         wind_speed: 4.77,
         wind_deg: 22,
         wind_gust: 3.87,
         weather: [
            {
               id: 800,
               main: 'Clear',
               description: 'clear sky',
               icon: '01d',
            },
         ],
         pop: 0,
      },
      {
         dt: 1692460800,
         temp: 34.5,
         feels_like: 32.6,
         pressure: 1015,
         humidity: 21,
         dew_point: 8.61,
         uvi: 1.75,
         clouds: 2,
         visibility: 10000,
         wind_speed: 5.26,
         wind_deg: 21,
         wind_gust: 3.71,
         weather: [
            {
               id: 800,
               main: 'Clear',
               description: 'clear sky',
               icon: '01d',
            },
         ],
         pop: 0,
      },
      {
         dt: 1692464400,
         temp: 32.99,
         feels_like: 31.27,
         pressure: 1016,
         humidity: 24,
         dew_point: 9.14,
         uvi: 0.52,
         clouds: 2,
         visibility: 10000,
         wind_speed: 5.04,
         wind_deg: 17,
         wind_gust: 4.37,
         weather: [
            {
               id: 800,
               main: 'Clear',
               description: 'clear sky',
               icon: '01d',
            },
         ],
         pop: 0,
      },
      {
         dt: 1692468000,
         temp: 30.88,
         feels_like: 29.52,
         pressure: 1016,
         humidity: 29,
         dew_point: 10,
         uvi: 0,
         clouds: 3,
         visibility: 10000,
         wind_speed: 3.83,
         wind_deg: 14,
         wind_gust: 3.92,
         weather: [
            {
               id: 800,
               main: 'Clear',
               description: 'clear sky',
               icon: '01d',
            },
         ],
         pop: 0,
      },
      {
         dt: 1692471600,
         temp: 28.28,
         feels_like: 27.7,
         pressure: 1017,
         humidity: 37,
         dew_point: 11.26,
         uvi: 0,
         clouds: 7,
         visibility: 10000,
         wind_speed: 3.17,
         wind_deg: 12,
         wind_gust: 3.66,
         weather: [
            {
               id: 800,
               main: 'Clear',
               description: 'clear sky',
               icon: '01n',
            },
         ],
         pop: 0,
      },
      {
         dt: 1692475200,
         temp: 26.67,
         feels_like: 26.82,
         pressure: 1018,
         humidity: 44,
         dew_point: 12.29,
         uvi: 0,
         clouds: 5,
         visibility: 10000,
         wind_speed: 2.54,
         wind_deg: 10,
         wind_gust: 3.13,
         weather: [
            {
               id: 800,
               main: 'Clear',
               description: 'clear sky',
               icon: '01n',
            },
         ],
         pop: 0,
      },
      {
         dt: 1692478800,
         temp: 25.79,
         feels_like: 25.65,
         pressure: 1018,
         humidity: 47,
         dew_point: 12.54,
         uvi: 0,
         clouds: 4,
         visibility: 10000,
         wind_speed: 1.97,
         wind_deg: 357,
         wind_gust: 2.22,
         weather: [
            {
               id: 800,
               main: 'Clear',
               description: 'clear sky',
               icon: '01n',
            },
         ],
         pop: 0,
      },
      {
         dt: 1692482400,
         temp: 25.06,
         feels_like: 24.87,
         pressure: 1019,
         humidity: 48,
         dew_point: 12.22,
         uvi: 0,
         clouds: 3,
         visibility: 10000,
         wind_speed: 1.41,
         wind_deg: 7,
         wind_gust: 1.5,
         weather: [
            {
               id: 800,
               main: 'Clear',
               description: 'clear sky',
               icon: '01n',
            },
         ],
         pop: 0,
      },
      {
         dt: 1692486000,
         temp: 24.51,
         feels_like: 24.27,
         pressure: 1019,
         humidity: 48,
         dew_point: 11.97,
         uvi: 0,
         clouds: 4,
         visibility: 10000,
         wind_speed: 1.16,
         wind_deg: 16,
         wind_gust: 1.23,
         weather: [
            {
               id: 800,
               main: 'Clear',
               description: 'clear sky',
               icon: '01n',
            },
         ],
         pop: 0,
      },
      {
         dt: 1692489600,
         temp: 24.02,
         feels_like: 23.76,
         pressure: 1018,
         humidity: 49,
         dew_point: 11.73,
         uvi: 0,
         clouds: 18,
         visibility: 10000,
         wind_speed: 0.85,
         wind_deg: 16,
         wind_gust: 0.91,
         weather: [
            {
               id: 801,
               main: 'Clouds',
               description: 'few clouds',
               icon: '02n',
            },
         ],
         pop: 0,
      },
      {
         dt: 1692493200,
         temp: 23.73,
         feels_like: 23.44,
         pressure: 1018,
         humidity: 49,
         dew_point: 11.57,
         uvi: 0,
         clouds: 100,
         visibility: 10000,
         wind_speed: 0.81,
         wind_deg: 33,
         wind_gust: 0.83,
         weather: [
            {
               id: 804,
               main: 'Clouds',
               description: 'overcast clouds',
               icon: '04n',
            },
         ],
         pop: 0,
      },
      {
         dt: 1692496800,
         temp: 23.37,
         feels_like: 23.07,
         pressure: 1018,
         humidity: 50,
         dew_point: 11.45,
         uvi: 0,
         clouds: 100,
         visibility: 10000,
         wind_speed: 0.29,
         wind_deg: 54,
         wind_gust: 0.72,
         weather: [
            {
               id: 804,
               main: 'Clouds',
               description: 'overcast clouds',
               icon: '04n',
            },
         ],
         pop: 0,
      },
      {
         dt: 1692500400,
         temp: 23.02,
         feels_like: 22.71,
         pressure: 1017,
         humidity: 51,
         dew_point: 11.33,
         uvi: 0,
         clouds: 100,
         visibility: 10000,
         wind_speed: 0.22,
         wind_deg: 180,
         wind_gust: 0.68,
         weather: [
            {
               id: 804,
               main: 'Clouds',
               description: 'overcast clouds',
               icon: '04n',
            },
         ],
         pop: 0,
      },
      {
         dt: 1692504000,
         temp: 22.64,
         feels_like: 22.29,
         pressure: 1017,
         humidity: 51,
         dew_point: 11.09,
         uvi: 0,
         clouds: 91,
         visibility: 10000,
         wind_speed: 0.56,
         wind_deg: 182,
         wind_gust: 0.73,
         weather: [
            {
               id: 804,
               main: 'Clouds',
               description: 'overcast clouds',
               icon: '04n',
            },
         ],
         pop: 0,
      },
      {
         dt: 1692507600,
         temp: 22.34,
         feels_like: 21.96,
         pressure: 1018,
         humidity: 51,
         dew_point: 10.87,
         uvi: 0,
         clouds: 80,
         visibility: 10000,
         wind_speed: 0.29,
         wind_deg: 213,
         wind_gust: 0.61,
         weather: [
            {
               id: 803,
               main: 'Clouds',
               description: 'broken clouds',
               icon: '04d',
            },
         ],
         pop: 0,
      },
      {
         dt: 1692511200,
         temp: 24.65,
         feels_like: 24.35,
         pressure: 1018,
         humidity: 45,
         dew_point: 10.88,
         uvi: 0.34,
         clouds: 68,
         visibility: 10000,
         wind_speed: 0.35,
         wind_deg: 287,
         wind_gust: 0.73,
         weather: [
            {
               id: 803,
               main: 'Clouds',
               description: 'broken clouds',
               icon: '04d',
            },
         ],
         pop: 0,
      },
      {
         dt: 1692514800,
         temp: 26.7,
         feels_like: 26.48,
         pressure: 1018,
         humidity: 36,
         dew_point: 9.71,
         uvi: 1.33,
         clouds: 0,
         visibility: 10000,
         wind_speed: 0.9,
         wind_deg: 340,
         wind_gust: 1.04,
         weather: [
            {
               id: 800,
               main: 'Clear',
               description: 'clear sky',
               icon: '01d',
            },
         ],
         pop: 0,
      },
      {
         dt: 1692518400,
         temp: 28.7,
         feels_like: 27.68,
         pressure: 1018,
         humidity: 31,
         dew_point: 8.97,
         uvi: 3.17,
         clouds: 0,
         visibility: 10000,
         wind_speed: 1.9,
         wind_deg: 23,
         wind_gust: 2,
         weather: [
            {
               id: 800,
               main: 'Clear',
               description: 'clear sky',
               icon: '01d',
            },
         ],
         pop: 0,
      },
      {
         dt: 1692522000,
         temp: 30.37,
         feels_like: 28.82,
         pressure: 1018,
         humidity: 26,
         dew_point: 8.24,
         uvi: 5.63,
         clouds: 0,
         visibility: 10000,
         wind_speed: 2.46,
         wind_deg: 27,
         wind_gust: 2.56,
         weather: [
            {
               id: 800,
               main: 'Clear',
               description: 'clear sky',
               icon: '01d',
            },
         ],
         pop: 0,
      },
      {
         dt: 1692525600,
         temp: 31.84,
         feels_like: 30.01,
         pressure: 1018,
         humidity: 23,
         dew_point: 7.48,
         uvi: 8.03,
         clouds: 0,
         visibility: 10000,
         wind_speed: 2.91,
         wind_deg: 24,
         wind_gust: 2.8,
         weather: [
            {
               id: 800,
               main: 'Clear',
               description: 'clear sky',
               icon: '01d',
            },
         ],
         pop: 0,
      },
      {
         dt: 1692529200,
         temp: 33.08,
         feels_like: 31.09,
         pressure: 1017,
         humidity: 21,
         dew_point: 7.01,
         uvi: 9.58,
         clouds: 0,
         visibility: 10000,
         wind_speed: 3.42,
         wind_deg: 35,
         wind_gust: 3.16,
         weather: [
            {
               id: 800,
               main: 'Clear',
               description: 'clear sky',
               icon: '01d',
            },
         ],
         pop: 0,
      },
      {
         dt: 1692532800,
         temp: 34,
         feels_like: 31.87,
         pressure: 1017,
         humidity: 19,
         dew_point: 6.89,
         uvi: 9.78,
         clouds: 0,
         visibility: 10000,
         wind_speed: 3.65,
         wind_deg: 39,
         wind_gust: 3.44,
         weather: [
            {
               id: 800,
               main: 'Clear',
               description: 'clear sky',
               icon: '01d',
            },
         ],
         pop: 0,
      },
      {
         dt: 1692536400,
         temp: 34.75,
         feels_like: 32.66,
         pressure: 1016,
         humidity: 19,
         dew_point: 7.01,
         uvi: 8.57,
         clouds: 0,
         visibility: 10000,
         wind_speed: 4.16,
         wind_deg: 39,
         wind_gust: 3.93,
         weather: [
            {
               id: 800,
               main: 'Clear',
               description: 'clear sky',
               icon: '01d',
            },
         ],
         pop: 0,
      },
      {
         dt: 1692540000,
         temp: 35.01,
         feels_like: 33.06,
         pressure: 1016,
         humidity: 20,
         dew_point: 7.88,
         uvi: 6.34,
         clouds: 0,
         visibility: 10000,
         wind_speed: 5.13,
         wind_deg: 38,
         wind_gust: 4.55,
         weather: [
            {
               id: 800,
               main: 'Clear',
               description: 'clear sky',
               icon: '01d',
            },
         ],
         pop: 0,
      },
      {
         dt: 1692543600,
         temp: 34.17,
         feels_like: 32.59,
         pressure: 1016,
         humidity: 24,
         dew_point: 9.68,
         uvi: 3.82,
         clouds: 0,
         visibility: 10000,
         wind_speed: 5.95,
         wind_deg: 36,
         wind_gust: 5.18,
         weather: [
            {
               id: 800,
               main: 'Clear',
               description: 'clear sky',
               icon: '01d',
            },
         ],
         pop: 0,
      },
   ],
   daily: [
      {
         dt: 1692356400,
         sunrise: 1692334570,
         sunset: 1692383070,
         moonrise: 1692340620,
         moonset: 1692387600,
         moon_phase: 0.06,
         summary: 'Expect a day of partly cloudy with clear spells',
         temp: {
            day: 37.75,
            min: 26,
            max: 38.14,
            night: 28.11,
            eve: 36.36,
            morn: 26,
         },
         feels_like: {
            day: 35.94,
            night: 27.91,
            eve: 35.14,
            morn: 26,
         },
         pressure: 1015,
         humidity: 18,
         dew_point: 8.6,
         wind_speed: 5.27,
         wind_deg: 341,
         wind_gust: 7.96,
         weather: [
            {
               id: 800,
               main: 'Clear',
               description: 'clear sky',
               icon: '01d',
            },
         ],
         clouds: 1,
         pop: 0.05,
         uvi: 10.13,
      },
      {
         dt: 1692442800,
         sunrise: 1692421019,
         sunset: 1692469395,
         moonrise: 1692430440,
         moonset: 1692475320,
         moon_phase: 0.09,
         summary: 'There will be clear sky today',
         temp: {
            day: 34.06,
            min: 25.06,
            max: 35.66,
            night: 25.06,
            eve: 32.99,
            morn: 25.64,
         },
         feels_like: {
            day: 32.23,
            night: 24.87,
            eve: 31.27,
            morn: 25.46,
         },
         pressure: 1016,
         humidity: 22,
         dew_point: 8.91,
         wind_speed: 5.26,
         wind_deg: 21,
         wind_gust: 4.37,
         weather: [
            {
               id: 800,
               main: 'Clear',
               description: 'clear sky',
               icon: '01d',
            },
         ],
         clouds: 0,
         pop: 0,
         uvi: 9.77,
      },
      {
         dt: 1692529200,
         sunrise: 1692507468,
         sunset: 1692555720,
         moonrise: 1692520320,
         moonset: 1692563100,
         moon_phase: 0.12,
         summary: 'Expect a day of partly cloudy with clear spells',
         temp: {
            day: 33.08,
            min: 22.34,
            max: 35.01,
            night: 24.45,
            eve: 30.95,
            morn: 22.34,
         },
         feels_like: {
            day: 31.09,
            night: 24.47,
            eve: 30.09,
            morn: 21.96,
         },
         pressure: 1017,
         humidity: 21,
         dew_point: 7.01,
         wind_speed: 5.96,
         wind_deg: 29,
         wind_gust: 5.51,
         weather: [
            {
               id: 800,
               main: 'Clear',
               description: 'clear sky',
               icon: '01d',
            },
         ],
         clouds: 0,
         pop: 0,
         uvi: 9.78,
      },
      {
         dt: 1692615600,
         sunrise: 1692593917,
         sunset: 1692642043,
         moonrise: 1692610200,
         moonset: 1692650940,
         moon_phase: 0.15,
         summary: 'There will be clear sky today',
         temp: {
            day: 33.16,
            min: 22.49,
            max: 33.16,
            night: 25.07,
            eve: 28.72,
            morn: 22.49,
         },
         feels_like: {
            day: 31.67,
            night: 25.07,
            eve: 28.25,
            morn: 22.2,
         },
         pressure: 1017,
         humidity: 26,
         dew_point: 10.54,
         wind_speed: 6.42,
         wind_deg: 26,
         wind_gust: 6.4,
         weather: [
            {
               id: 800,
               main: 'Clear',
               description: 'clear sky',
               icon: '01d',
            },
         ],
         clouds: 0,
         pop: 0,
         uvi: 9.44,
      },
      {
         dt: 1692702000,
         sunrise: 1692680365,
         sunset: 1692728366,
         moonrise: 1692700260,
         moonset: 1692738900,
         moon_phase: 0.19,
         summary:
            'You can expect clear sky in the morning, with partly cloudy in the afternoon',
         temp: {
            day: 32.65,
            min: 22.46,
            max: 34.12,
            night: 27.03,
            eve: 29.95,
            morn: 23.93,
         },
         feels_like: {
            day: 30.9,
            night: 27.1,
            eve: 29.21,
            morn: 23.74,
         },
         pressure: 1015,
         humidity: 24,
         dew_point: 8.56,
         wind_speed: 5.11,
         wind_deg: 54,
         wind_gust: 5.86,
         weather: [
            {
               id: 800,
               main: 'Clear',
               description: 'clear sky',
               icon: '01d',
            },
         ],
         clouds: 0,
         pop: 0.03,
         uvi: 8.58,
      },
      {
         dt: 1692788400,
         sunrise: 1692766814,
         sunset: 1692814688,
         moonrise: 1692790440,
         moonset: 1692827220,
         moon_phase: 0.22,
         summary: 'Expect a day of partly cloudy with rain',
         temp: {
            day: 34.02,
            min: 23.25,
            max: 34.28,
            night: 27.58,
            eve: 30.46,
            morn: 25.04,
         },
         feels_like: {
            day: 31.9,
            night: 27.14,
            eve: 29.11,
            morn: 24.72,
         },
         pressure: 1014,
         humidity: 19,
         dew_point: 6.53,
         wind_speed: 4.63,
         wind_deg: 23,
         wind_gust: 4.21,
         weather: [
            {
               id: 500,
               main: 'Rain',
               description: 'light rain',
               icon: '10d',
            },
         ],
         clouds: 81,
         pop: 0.37,
         rain: 0.61,
         uvi: 9,
      },
      {
         dt: 1692874800,
         sunrise: 1692853262,
         sunset: 1692901009,
         moonrise: 1692880860,
         moonset: 1692915960,
         moon_phase: 0.25,
         summary: 'Expect a day of partly cloudy with rain',
         temp: {
            day: 34.75,
            min: 24.72,
            max: 34.75,
            night: 25.65,
            eve: 29.15,
            morn: 26.21,
         },
         feels_like: {
            day: 32.66,
            night: 25.42,
            eve: 28.19,
            morn: 26.21,
         },
         pressure: 1014,
         humidity: 19,
         dew_point: 6.74,
         wind_speed: 6.98,
         wind_deg: 356,
         wind_gust: 6.14,
         weather: [
            {
               id: 802,
               main: 'Clouds',
               description: 'scattered clouds',
               icon: '03d',
            },
         ],
         clouds: 32,
         pop: 0.17,
         uvi: 9,
      },
      {
         dt: 1692961200,
         sunrise: 1692939710,
         sunset: 1692987329,
         moonrise: 1692971340,
         moonset: 0,
         moon_phase: 0.29,
         summary: 'Expect a day of partly cloudy with clear spells',
         temp: {
            day: 35.51,
            min: 23.51,
            max: 36.77,
            night: 28.13,
            eve: 31.21,
            morn: 25,
         },
         feels_like: {
            day: 33.27,
            night: 27.34,
            eve: 29.69,
            morn: 24.65,
         },
         pressure: 1012,
         humidity: 17,
         dew_point: 6.5,
         wind_speed: 3.48,
         wind_deg: 12,
         wind_gust: 4.43,
         weather: [
            {
               id: 800,
               main: 'Clear',
               description: 'clear sky',
               icon: '01d',
            },
         ],
         clouds: 0,
         pop: 0,
         uvi: 9,
      },
   ],
   alerts: [
      {
         sender_name: 'Office National de la Météorologie',
         event: 'ORAGE',
         start: 1692381600,
         end: 1692392400,
         description: '',
         tags: ['Thunderstorm'],
      },
      {
         sender_name: 'Office National de la Météorologie',
         event: 'PLUIE',
         start: 1692381600,
         end: 1692392400,
         description: '',
         tags: ['Rain'],
      },
   ],
};
